![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. Pandas kutubxonasi.

### PANDAS. Yakuniy vazifa. **2-Qism**

## Dataset
#### Ushbu vazifada biz turli davlatlarning turli yillarda elektr tokini qanday manbaalardan olganini ko'rsatuvchi jadval bilan ishlaymiz.
Jadval ustunlari ko'mir, gaz, gidro va boshqa manbaalardan ko'rsatilgan yilda qancha __terravat/soat__ energiya olinganini ko'rsatadi.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/Electricity_Production_By_Source.csv")
df.columns = ['davlat','kod','yil','komir','gaz','gidro','yangilanuvchi','quyosh','neft','shamol','atom']
df.head()

,davlat,kod,yil,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
0,Afghanistan,AFG,2000,0.0,0.155,0.312,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,AFG,2001,0.0,0.094,0.498,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,AFG,2002,0.0,0.132,0.555,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,AFG,2003,0.0,0.309,0.630,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,2004,0.0,0.329,0.565,0.0,0.0,0.0,0.0,0.0

### 1-VAZIFA. DF hajmini chiqaring

In [4]:
print(df.shape)

(6241, 11)

### 2-VAZIFA. Jadvalda mavjud davlatlar ro'yxatini alohida chiqaring

In [6]:
countries = df['davlat'].unique()
display(countries)

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'American Samoa',
       'Angola', 'Antarctica', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Aruba', 'Asia Pacific', 'Australia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'CIS', 'Cambodia', 'Cameroon', 'Canada',
       'Cayman Islands', 'Central African Republic', 'Central America',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus',
       'Czechia', 'Democratic Republic of Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'EU-27', 'EU27+1',
       'Eastern Africa', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Europe',
       'Europe (other)', 'Falkland Islands', 'Faroe Islands', 'Fiji',
       'Finland', 'France', 'French Guiana', 'French Polynesia', 'Gabon',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece',
       'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
       'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Lithuania', 'Luxembourg', 'Macau', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Martinique',
       'Mauritania', 'Mauritius', 'Mexico', 'Middle Africa',
       'Middle East', 'Moldova', 'Mongolia', 'Montenegro', 'Montserrat',
       'Morocco', 'Mozambique', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'Netherlands Antilles', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue',
       'North America', 'North Korea', 'North Macedonia', 'Norway',
       'Oman', 'Other Asia & Pacific', 'Other CIS', 'Other Caribbean',
       'Other Middle East', 'Other Northern Africa',
       'Other South America', 'Other Southern Africa', 'Pakistan',
       'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Reunion', 'Romania', 'Russia', 'Rwanda', 'Saint Helena',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia',
       'Slovenia', 'Solomon Islands', 'Somalia',
       'South & Central America', 'South Africa', 'South Korea',
       'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
       'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Turkmenistan', 'Turks and Caicos Islands',
       'U.S. Pacific Islands', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela', 'Vietnam', 'Western Africa', 'Western Sahara',
       'World', 'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

### 3-VAZIFA. DF dan faqat AQSh (`United States`) uchun ma'lumotlarni ajratib oling va yangi `dfus` nomli o'zgaruvchiga saqlang

In [7]:
dfus = df[df['davlat'] == 'United States']
display(dfus.head())

,davlat,kod,yil,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
5887,United States,USA,1985,1507.664651,313.920392,287.182362,36.392894,0.010737,107.744380,0.005820,403.884976
5888,United States,USA,1986,1490.141346,267.213369,296.974969,38.701672,0.014174,146.865448,0.004231,435.829540
5889,United States,USA,1987,1573.958375,293.140648,255.410195,42.665433,0.010603,127.411367,0.003577,479.231981
5890,United States,USA,1988,1656.615886,271.828714,228.384649,42.394061,0.009186,160.107055,0.000880,554.708470
5891,United States,USA,1989,1711.442534,379.170824,274.724178,48.854268,0.253132,176.729591,2.133377,557.215492

### 4-VAZIFA. `dfus` jadvalining indeksini `yil` ustuni bilan o'zgartiring. DF dan `yil` ustunini tashlab yuboring.

In [8]:
dfus.set_index('yil', inplace=True)
display(dfus.head())

,davlat,kod,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
yil,,,,,,,,,,
1985,United States,USA,1507.664651,313.920392,287.182362,36.392894,0.010737,107.744380,0.005820,403.884976
1986,United States,USA,1490.141346,267.213369,296.974969,38.701672,0.014174,146.865448,0.004231,435.829540
1987,United States,USA,1573.958375,293.140648,255.410195,42.665433,0.010603,127.411367,0.003577,479.231981
1988,United States,USA,1656.615886,271.828714,228.384649,42.394061,0.009186,160.107055,0.000880,554.708470
1989,United States,USA,1711.442534,379.170824,274.724178,48.854268,0.253132,176.729591,2.133377,557.215492

### 5-VAZIFA. AQSh 2020-yilda jami qancha elektr energiyasi ishlab chiqqan?

In [10]:
total_production_2020 = dfus.loc[2020, ['komir', 'gaz', 'gidro', 'yangilanuvchi', 'quyosh', 'neft', 'shamol', 'atom']].sum()
display(total_production_2020)

np.float64(4049.84653732)

### 6-VAZIFA. 2010-2020-yillarda AQSH turli manbaalardan o'rtacha qancha elektr toki olganini chiqaring. Natijani kichikdan kattaga qarab tartiblang.

In [11]:
avg_production_2010_2020 = dfus.loc[2010:2020, ['komir', 'gaz', 'gidro', 'yangilanuvchi', 'quyosh', 'neft', 'shamol', 'atom']].mean()
display(avg_production_2010_2020.sort_values())

neft               39.028512
quyosh             49.943642
yangilanuvchi      75.785131
shamol            207.386225
gidro             273.634436
atom              796.992746
gaz              1299.518378
komir            1358.154104
dtype: float64

### 7-VAZIFA. AQSH gidro elektr stansiyalardan eng kam va eng ko'p elektr energiyasi olgan yillarni toping.

In [12]:
min_gidro_year = dfus['gidro'].idxmin()
max_gidro_year = dfus['gidro'].idxmax()

print(f"Eng kam gidro energiya olingan yil: {min_gidro_year}")
print(f"Eng ko'p gidro energiya olingan yil: {max_gidro_year}")

Eng kam gidro energiya olingan yil: 2001
Eng ko'p gidro energiya olingan yil: 1997

### 8-VAZIFA.
#### 8.1 Asl `df` dan 2019-yil ma'lumotlarini ajratib oling.
#### 8.2 Yangi df ga `df19` deb nom bering
#### 8.3 `df19` indeksini `davlat` ustuniga o'zgartiring hamda `davlat` va `yil` ustunlarini tashlab yuboring.
#### 8.4 `df19` dan `World` indeksini o'chirib tashlang

In [14]:
df19 = df[df['yil'] == 2019].copy()
df19.set_index('davlat', inplace=True)
df19.drop(columns=['yil'], inplace=True)
df19.drop('World', inplace=True)
display(df19.head())

,kod,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
davlat,,,,,,,,,
Afghanistan,AFG,0.000000,0.152000,0.840000,0.000000,0.040000,0.00000,0.000000,0.000000
Africa,NaN,253.555978,340.472820,132.734791,8.184247,19.377978,81.27424,17.508052,14.214193
Albania,ALB,0.000000,0.000000,5.153940,0.000000,0.022000,0.00000,0.000000,0.000000
Algeria,DZA,0.000000,73.615787,0.106440,0.000000,0.615000,0.00000,0.011000,0.000000
American Samoa,ASM,0.000000,0.000000,0.000000,0.000000,0.000000,0.16300,0.000000,0.000000

#### 8.5 `df19` jadvali uchun umumlashtiruvchi statistikani chiqaring

In [15]:
display(df19.describe())

,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
count,225.000000,225.000000,234.000000,233.000000,234.000000,225.000000,234.000000,234.000000
mean,89.629863,63.570115,40.428494,7.378199,7.297140,10.575434,15.621916,30.370740
std,590.143698,224.662108,169.370944,29.920512,35.365822,36.389645,70.427073,136.481831
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.003195,0.042000,0.000000,0.000000
50%,0.000000,0.229147,0.991647,0.031000,0.040000,0.620333,0.008250,0.000000
75%,4.420929,20.635015,11.910820,1.314232,0.762633,3.872553,1.136484,0.000000
max,7376.390586,1975.752363,1783.656628,238.022873,393.921841,396.115102,514.259616,963.746826

### 9-VAZIFA. 2019-yilda har bir davlat jami qancha elektr energiya ishlab chiqarganini DF ko'rinishida chiqaring.
*ishora. `Series` obyektini `DF` ga o'tkazing

In [16]:
total_production_2019 = df19.drop(columns=['kod']).sum(axis=1)
total_production_2019_df = total_production_2019.to_frame(name='total_production')
display(total_production_2019_df.sort_values(by='total_production', ascending=False))

                total_production
davlat
Asia Pacific        12575.717147
China                7326.700000
North America        5389.510269
United States        4161.834262
Europe               3916.115519
...                          ...
Montserrat              0.013667
Saint Helena            0.008333
Niue                    0.003000
Antarctica              0.000000
Western Sahara          0.000000

[234 rows x 1 columns]

### 10-VAZIFA.
#### 10.1. Asl DF dan 2000-2020-yillar, `France` uchun `atom`, `komir`, `gaz`, `quyosh` manbaalarini alohida `dffr` jadvaliga ko'chirib oling
#### 10.2. `dffr` jadvalini yil ustuni bo'yicha tartiblang

In [17]:
dffr = df[(df['davlat'] == 'France') & (df['yil'] >= 2000) & (df['yil'] <= 2020)][['yil', 'atom', 'komir', 'gaz', 'quyosh']].copy()
dffr.sort_values(by='yil', inplace=True)
display(dffr)

       yil        atom      komir        gaz     quyosh
1934  2000  415.162000  27.004000  11.514000   0.005223
1935  2001  421.076000  20.478000  15.146000   0.006161
1936  2002  436.760000  23.658000  18.369000   0.007104
1937  2003  441.070000  26.260000  19.368000   0.007767
1938  2004  448.241000  24.372000  21.049000   0.008448
1939  2005  451.529000  27.515000  23.069000   0.010501
1940  2006  450.191000  22.889000  21.760000   0.012103
1941  2007  439.730000  24.446000  21.987000   0.017572
1942  2008  439.447000  23.063000  21.884000   0.041692
1943  2009  409.736000  21.667000  20.503000   0.173971
1944  2010  428.521000  23.359000  23.758000   0.620000
1945  2011  442.387763  17.807444  29.489144   2.333802
1946  2012  425.406017  21.449981  22.753254   4.427930
1947  2013  423.684671  23.830994  18.393269   5.193590
1948  2014  436.479009  11.242305  13.162876   6.391477
1949  2015  437.427808  11.873673  21.143153   7.753328
1950  2016  403.195482  10.344460  34.967086   8.659160
1951  2017  398.359129  12.818153  40.500366   9.584882
1952  2018  412.941812   8.412694  30.587768  10.568737
1953  2019  398.941812   4.412694  37.587768  12.568737
1954  2020  355.190804   4.275487  34.245560  13.190057

#### 10.3 `dffr`uchun Korrelyasiya jadvalini chiqaring.

In [18]:
display(dffr.corr())

             yil      atom     komir       gaz    quyosh
yil     1.000000 -0.606801 -0.866541  0.732072  0.918831
atom   -0.606801  1.000000  0.677929 -0.561700 -0.726689
komir  -0.866541  0.677929  1.000000 -0.665521 -0.933234
gaz     0.732072 -0.561700 -0.665521  1.000000  0.706133
quyosh  0.918831 -0.726689 -0.933234  0.706133  1.000000