![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. Pandas kutubxonasi.

### PANDAS. Yakuniy vazifa. **1-QISM**

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population.csv", index_col=0)

### 1-VAZIFA. Yuqoridagi DF ustunlari nomini quyidagi qiymatlarga o'zgartiring va DF yuqorisidan 3 ta davlatni chiqaring
`['davlat','zichlik_km','zichlik_mi','aholi','maydoni']`

In [4]:
df.columns = ['davlat','zichlik_km','zichlik_mi','aholi','maydoni']
df.head(3)

         davlat  zichlik_km  zichlik_mi     aholi  maydoni
rank
1         Macau  21946.4667  56841.3487   658.394       30
2        Monaco  19755.5000  51166.7450    39.511        2
3     Singapore   8305.1915  21510.4461  5896.686      710

## Yuqoridagi jadval dunyo davlatlarining aholi zichligi bo'yicha reytingini ko'rsatadi.
DF indeksi sifatida davlatning zichlik reytingi olingan (aholi eng zich yashaydigan davlatlar yuqorida).

**Ustunlar:**

`davlat` - Davlat nomi

`zichlik_km` - har 1 kv.km. ga to'g'ri keluvchi aholi soni

`zichlik_mi` - har 1 kv.milyaga to'g'ri keluvchi aholi soni (milya - AQSh masofa o'lchov birligi)

`aholi` - 2021-yilga ko'rsa aholi soni (ming)

`maydoni` - davlat maydoni (kv.km)

### 2-VAZIFA. DF oxiridan 10 ta qator chiqaring.

In [5]:
column = df.columns
df.tail(10)

                davlat  zichlik_km  zichlik_mi      aholi  maydoni
rank
223             Guyana      3.6765      9.5220    790.326   214969
224      French Guiana      3.6685      9.5015    306.448    83534
225           Suriname      3.6125      9.3564    591.800   163820
226          Australia      3.3526      8.6832  25788.215  7692024
227            Iceland      3.3335      8.6338    343.353   103000
228            Namibia      3.1338      8.1166   2587.344   825615
229     Western Sahara      2.3003      5.9577    611.875   266000
230           Mongolia      2.1286      5.5129   3329.289  1564110
231   Falkland Islands      0.2902      0.7517      3.533    12173
232          Greenland      0.0263      0.0680     56.877  2166086

### 3-VAZIFA. DF dan 10, 20, 100, 200-indekslarda turgan davlatlarni alohida DF ko'rinishida chiqaring.

In [6]:
index = [10,20,100,200]
df.iloc[index]

          davlat  zichlik_km  zichlik_mi       aholi  maydoni
rank
11    Bangladesh   1126.9465   2918.7915  166303.498   147570
21    San Marino    557.6557   1444.3284      34.017       61
101        Benin    110.5560    286.3401   12451.040   112622
201     Paraguay     17.7495     45.9712    7219.638   406752

### 4-VAZIFA. Davlatlar orasida `Uzbekistan`, `Hong-Kong`, `Antartica` borligini tekshiring

In [31]:
states = ['Uzbekistan', 'Hong-Kong', 'Antartica']
countries_to_check = ['Uzbekistan', 'Hong Kong', 'Antarctica']

for country in countries_to_check:
    # Corrected line to check existence in the 'state' DataFrame's index
    if country in state.index:
        print(f"{country}: Found")
    else:
        print(f"{country}: Not Found")

Uzbekistan: Found
Hong Kong: Found
Antarctica: Not Found

### 5-VAZIFA.
#### 5.1 DFning `davlat` nomli ustunini uning indeksi qilib belgilang.
#### 5.2 `davlat` ustunini tashlab yuboring.
#### 5.3 DFni davlat nomi bo'yicha tartiblang

In [8]:
state = df.set_index('davlat')
state.head()

           zichlik_km  zichlik_mi     aholi  maydoni
davlat
Macau      21946.4667  56841.3487   658.394       30
Monaco     19755.5000  51166.7450    39.511        2
Singapore   8305.1915  21510.4461  5896.686      710
Hong Kong   6841.3134  17719.0017  7552.810     1104
Gibraltar   5616.3333  14546.3033    33.698        6

### 6-VAZIFA. DF dan `Uzbekistan`, `Malaysia`, `South Korea`, `France` davlatlari `aholi` va `maydoni` ustunlari bilan alohida DF ko'rinishida ajratib oling.

In [9]:
Uzbekistan = state.loc['Uzbekistan']
Malaysia = state.loc['Malaysia']
South_Korea = state.loc['South Korea']
France = state.loc['France']

### 7-VAZIFA. Asl DFning `aholi` ustuni qiymatlarini 1000 ga ko'paytiring.

In [10]:
population = df['aholi']*1000
population

rank
1       658394.0
2        39511.0
3      5896686.0
4      7552810.0
5        33698.0
         ...
228    2587344.0
229     611875.0
230    3329289.0
231       3533.0
232      56877.0
Name: aholi, Length: 232, dtype: float64

DF ni `aholi` ustuni bo'yicha kamayish tartibida tahlang va aholisi eng kam 10 ta davlatni chiqaring.

In [11]:
population.sort_values(ascending=False).head(10)

rank
82     1.444216e+09
29     1.393409e+09
174    3.329151e+08
83     2.763618e+08
53     2.251999e+08
189    2.139934e+08
63     2.114007e+08
11     1.663035e+08
214    1.459120e+08
144    1.302622e+08
Name: aholi, dtype: float64

### 8-VAZIFA. DFni `maydoni` bo'yicha reytinglang (rank) va reytinglarni yangi `rank` ustuniga yozing.

In [12]:
field = df.sort_values(by='maydoni', ascending=False)
field['rank'] = field['maydoni'].rank()
field

             davlat  zichlik_km  zichlik_mi        aholi   maydoni   rank
rank
214          Russia      8.5337     22.1024   145912.025  17098242  232.0
222          Canada      3.8126      9.8747    38067.903   9984670  231.0
82            China    148.7815    385.3441  1444216.107   9706961  230.0
174   United States     35.5200     91.9968   332915.073   9372610  229.0
189          Brazil     25.1291     65.0843   213993.437   8515767  228.0
...             ...         ...         ...          ...       ...    ...
22            Nauru    517.9048   1341.3733       10.876        21    5.5
98          Tokelau    114.4167    296.3392        1.373        12    4.0
5         Gibraltar   5616.3333  14546.3033       33.698         6    3.0
2            Monaco  19755.5000  51166.7450       39.511         2    2.0
13     Vatican City    800.0000   2072.0000        0.800         1    1.0

[232 rows x 6 columns]

#### `Uzbekistan`, `United Kingdom`, `Indonesia` davlatlari alohida df ko'rinishida chiqaring

In [14]:
countries_to_extract = ['Uzbekistan', 'United Kingdom', 'Indonesia']
extracted_countries_df = field[field['davlat'].isin(countries_to_extract)]
extracted_countries_df

              davlat  zichlik_km  zichlik_mi       aholi  maydoni   rank
rank
83         Indonesia    145.1046    375.8210  276361.783  1904569  218.0
133       Uzbekistan     75.8511    196.4542   33935.763   447400  176.0
49    United Kingdom    280.8033    727.2805   68207.116   242900  153.0

### 9-VAZIFA. DFni `davlat` nomi bo'yicha tartiblang.

In [15]:
df.sorted_names = df.sort_values(by='davlat')
df.sorted_names

/tmp/ipykernel_350/2410655152.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.sorted_names = df.sort_values(by='davlat')

                 davlat  zichlik_km  zichlik_mi      aholi  maydoni
rank
149         Afghanistan     61.0757    158.1862  39835.428   652230
111             Albania     99.9351    258.8318   2872.933    28748
198             Algeria     18.7328     48.5179  44616.624  2381741
50       American Samoa    276.8844    717.1307     55.100      199
78              Andorra    165.2885    428.0971     77.355      468
...                 ...         ...         ...        ...      ...
131   Wallis and Futuna     78.1268    202.3483     11.094      142
229      Western Sahara      2.3003      5.9577    611.875   266000
151               Yemen     57.7509    149.5749  30490.640   527968
188              Zambia     25.1400     65.1125  18920.651   752612
173            Zimbabwe     38.6229    100.0333  15092.171   390757

[232 rows x 5 columns]

#### DFdan 10,50,100,200-o'rinda turgan davlatlarni alohida DF ko'rinishida chiqaring

In [16]:
davlat = df.sorted_names
davlat.iloc[[10,50,100,200]]

              davlat  zichlik_km  zichlik_mi      aholi  maydoni
rank
20             Aruba    595.5778   1542.5464    107.204      180
87    Czech Republic    135.9862    352.2044  10724.555    78865
52           Jamaica    270.5362    700.6887   2973.463    10991
114            Syria     98.6916    255.6111  18275.702   185180

### 10-VAZIFA. Quyidagi davlatlarning `aholi` sonini oddiy son ko'rinishida chiqaring:
- `Malaysia`
- `Nigeria`
- `Nepal`
- `Italy`

In [32]:
countries = ['Malaysia', 'Nigeria', 'Nepal', 'Italy']
population_data = state.loc[countries, 'aholi'] * 1000
print(population_data)

davlat
Malaysia     32776194.0
Nigeria     211400708.0
Nepal        29674920.0
Italy        60367477.0
Name: aholi, dtype: float64